version: '3.5'

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5002:5000
    env_file:
      - ./.env.prod
    depends_on:
      - web-db

  web-db:
    container_name: web-db
    build:
      context: ./web-db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
