version: '3.5'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - web-db

  web-db:
    container_name: web-db
    build:
      context: ./web-db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - ./.env.prod.db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1337:8080
    depends_on:
      - web
